### ISSUE TITLE
Buddy your number is in public

### ISSUE THREAD

**Issue by PtPrashantTripathi** [peddidhanush/simple-login-and-registration-form-using-nodejs-and-mongodb#1]
*Hi buddy your accidentally pushed you personal mobile number in public repo it's not a best practice, kindly edit this line and append the commit so it will no longer available for anyone*

https://github.com/peddidhanush/simple-login-and-registration-form-using-nodejs-and-mongodb/blob/fee9140e23a8d8f46c7f0cb94b3ad21bc01e78c3/users.json#L1

**Comment by peddidhanush** [comment]
Thanks @PtPrashantTripathi i will edit this line
